export const ADD_COURSE_TO_COMPARE = "ADD_COURSE_TO_COMPARE";
export const REMOVED_COURSE_FROM_COMPARE = "REMOVED_COURSE_FROM_COMPARE";
export const SELECTED_COURSE_FOR_SEARCH = "SELECTED_FOR_SEARCH";
export const ADD_COURSE_TO_CART = "ADD_COURSE_TO_CART";
export const REMOVED_COURSE_FROM_CART = "REMOVED_COURSE_FROM_CART";
